[2021.10.07]
yeoonjae/java_algorithm pull request #1
Opened 2021-10-07 17:21 UTC by yeoonjae

- 프로그래머스 내적, 없는숫자더하기 (level.1)
 - 백준 짐챙기는 숌

2021-10-09 13:03 UTC, f-lab-jd commented on src/week09/없는숫자더하기.java
> +        int number[] = {1, 2, 3, 4, 6, 7, 8, 0};
C 언어 스타일로 배열을 선언해주셨는데요 ㅎㅎ Java 언어스타일로 수정하면 아래와 같습니다.
```
int[] number = {1, 2, 3, 4, 6, 7, 8, 0};
```

그리고 배열이니 복수형으로 numbers  라고 네이밍하면 더 좋을 것 같습니다. (cc. @ypr821 )

2021-10-09 13:06 UTC, f-lab-jd commented on src/week09/짐챙기는숌.java
> +        int count = 1;
좀더 명확하게 `boxCount` 로 해주셔도 좋을 것 같습니다. 
https://github.com/yeoonjae/java_algorithm/pull/1/files#diff-0518781fc4e9e9f2bb43f74c0e278ec15cd74a262df41a420536371e075dbf2cR17
바로 위에 똑같이 카운트 결과를 담는 변수는 cnt (약어) 로 적어주셨는데요.
하나의 클래스 안에서 풀네임/약어를 일관성있게 가져가는 습관을 들이는게 중요합니다.

2021-10-09 13:09 UTC, f-lab-jd commented on src/week09/짐챙기는숌.java
> +        int box = 0;
주석을 제가 잘 이해한게 맞다면.. `bookWeight` 이 되어야하지 않을까요~? 
(cc. @ypr821 )

2021-10-09 13:09 UTC, f-lab-jd commented on src/week09/짐챙기는숌.java
> +                int book = Integer.parseInt(st.nextToken());
마찬가지로 `bookWeight` 이면 더 명확하고 좋을 것 같습니다.
(cc. @ypr821 )

2021-10-09 13:11 UTC, f-lab-jd commented on src/week09/내적.java
> +        int[] a = {-1,0,1};
IDE 포맷터가 잘 적용된걸까요~? ㅎㅎ

2021-10-09 13:12 UTC, f-lab-jd requested changes
고생하셨습니다 👍 
반드시 고쳐야하는 내용은 아니지만, 리뷰 드린 내용 참고해서 수정해주시면 Approve 하겠습니다.

2021-10-10 04:39 UTC, yeoonjae commented on src/week09/없는숫자더하기.java
> +        int number[] = {1, 2, 3, 4, 6, 7, 8, 0};
앗 자바스타일 배열 선언이 있는 줄 처음 알았습니다! ㅎㅎ 이제 인지하고 사용하도록 하겠습니다~!

2021-10-10 09:40 UTC, f-lab-jd approved these changes
👍

2021-10-10 09:45 UTC, merged